# Generated by Django 6.0.2 on 2026-03-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orga', '0001_initial'),
        ('personalstamm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kostenstellen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kostenstelle', models.CharField(max_length=20, unique=True, verbose_name='Kostenstelle')),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('produktzuordnung', models.CharField(blank=True, max_length=50, null=True, verbose_name='Produktzuordnung')),
                ('zuordnungRechnungshof', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zuordnung Rechnungshof')),
                ('zuordnungGutachten', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zuordnung Gutachten')),
                ('stellenbemessungvom', models.DateTimeField(blank=True, null=True, verbose_name='Stellenbemessung vom')),
                ('stellenbemessung', models.FileField(blank=True, null=True, upload_to=None, verbose_name='Stellenbemessung (z.B. Dokumentation der Berechnung)')),
            ],
            options={
                'verbose_name': 'Kostenstelle',
                'verbose_name_plural': 'Kostenstellen',
                'db_table': 'Kostenstellen',
            },
        ),
        migrations.CreateModel(
            name='Stellenarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stellenart', models.SmallIntegerField(verbose_name='Stellenart-Code')),
                ('stellenart_bez', models.CharField(max_length=255, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Stellenart',
                'verbose_name_plural': 'Stellenarten',
                'db_table': 'Stellenarten',
            },
        ),
        migrations.CreateModel(
            name='Haushalte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushalt', models.CharField(max_length=50, unique=True, verbose_name='Haushalts-Kürzel')),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('haushaltsjahr', models.IntegerField(verbose_name='Haushaltsjahr')),
                ('nachtrag', models.BooleanField(default=False, verbose_name='Nachtrag')),
                ('verabschiedet', models.DateTimeField(blank=True, null=True, verbose_name='Verabschiedet am')),
                ('genehmigt', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigt am')),
                ('planung_abgeschlossen', models.BooleanField(default=False, verbose_name='Planung abgeschlossen')),
                ('arbeitstage', models.SmallIntegerField(blank=True, null=True, verbose_name='Arbeitstage/Jahr')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orga.gemeinden', verbose_name='Gemeinde')),
            ],
            options={
                'verbose_name': 'Haushalt',
                'verbose_name_plural': 'Haushalte',
                'db_table': 'Haushalte',
            },
        ),
        migrations.CreateModel(
            name='Stellenplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField(verbose_name='Haushaltsjahr')),
                ('stelle_nr', models.CharField(max_length=50, verbose_name='Stellennummer')),
                ('stelle_nr_vj', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stellennummer Vorjahr')),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Stellenbezeichnung')),
                ('einrichtungsdatum', models.DateTimeField(blank=True, null=True, verbose_name='Eingerichtet am')),
                ('letzte_neubewertung', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Neubewertung')),
                ('kw', models.BooleanField(default=False, verbose_name='Künftig wegfallend (kw)')),
                ('ku', models.BooleanField(default=False, verbose_name='Künftig umzuwandeln (ku)')),
                ('bemerkungen_druck', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen (Druck)')),
                ('stellenverweisung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stellenverweisung')),
                ('bemerkungen_int', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen (intern)')),
                ('produkt', models.IntegerField(blank=True, null=True, verbose_name='Produkt-ID')),
                ('kostentraeger', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kostenträger')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orga.gemeinden', verbose_name='Gemeinde')),
                ('kostenstelle', models.ManyToManyField(blank=True, null=True, to='stellenplan.kostenstellen', verbose_name='Kostenstelle')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orga.organisationseinheiten', verbose_name='Organisationseinheit')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stellenplan.haushalte', verbose_name='Haushaltsplan')),
                ('stellenart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stellenplan.stellenarten', verbose_name='Stellenart')),
                ('verg_grp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personalstamm.verggrp', verbose_name='Vergütungsgruppe')),
            ],
            options={
                'verbose_name': 'Stelle',
                'verbose_name_plural': 'Stellenplan',
                'db_table': 'Stellenplan',
            },
        ),
        migrations.CreateModel(
            name='Stellenbesetzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField(verbose_name='Haushaltsjahr')),
                ('besetzungsart', models.IntegerField(blank=True, null=True, verbose_name='Besetzungsart')),
                ('besetzung_ab', models.DateTimeField(blank=True, null=True, verbose_name='Besetzt ab')),
                ('besetzung_bis', models.DateTimeField(blank=True, null=True, verbose_name='Besetzt bis')),
                ('stunden', models.IntegerField(blank=True, null=True, verbose_name='Wochenstunden')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personalstamm.personalstamm', verbose_name='Mitarbeiter')),
                ('stelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stellenplan.stellenplan', verbose_name='Stelle')),
            ],
            options={
                'verbose_name': 'Stellenbesetzung',
                'verbose_name_plural': 'Stellenbesetzungen',
                'db_table': 'Stellenbesetzung',
            },
        ),
        migrations.CreateModel(
            name='KostenstellenaufteilungStellen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufteilung_prozent', models.FloatField(blank=True, default=100.0, null=True, verbose_name='Aufteilung (%)')),
                ('gueltig_ab', models.DateTimeField(verbose_name='Gültig ab')),
                ('gueltig_bis', models.DateTimeField(blank=True, null=True, verbose_name='Gültig bis')),
                ('kostenstelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellenplan.kostenstellen', verbose_name='Kostenstelle')),
                ('stelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellenplan.stellenplan', verbose_name='Stelle')),
            ],
            options={
                'verbose_name': 'Kostenstellenaufteilung',
                'verbose_name_plural': 'Kostenstellenaufteilungen',
                'db_table': 'KostenstellenaufteilungStellen',
            },
        ),
        migrations.CreateModel(
            name='StellenplanSoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buchungsdatum', models.DateField(verbose_name='Buchungsdatum')),
                ('erfassungsdatum', models.DateTimeField(auto_now_add=True, verbose_name='Erfassungsdatum')),
                ('stellensoll_hhj', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Stellensoll HHJ (Anteile VZAE)')),
                ('aend_stellensoll_hhj', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Änderung Stellensoll')),
                ('aend_ab', models.DateTimeField(blank=True, null=True, verbose_name='Änderung gültig ab')),
                ('ps_bemerkungen', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stellenplan.haushalte', verbose_name='Haushaltsplan')),
                ('stelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stellenplan.stellenplan', verbose_name='Stelle')),
            ],
            options={
                'verbose_name': 'Stellenplan-Soll',
                'db_table': 'StellenplanSoll',
            },
        ),
        migrations.CreateModel(
            name='Teilhaushalte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField(verbose_name='Haushaltsjahr')),
                ('th', models.CharField(max_length=50, verbose_name='TH-Kürzel')),
                ('th_bezeichnung', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orga.gemeinden', verbose_name='Gemeinde')),
            ],
            options={
                'verbose_name': 'Teilhaushalt',
                'verbose_name_plural': 'Teilhaushalte',
                'db_table': 'Teilhaushalte',
            },
        ),
        migrations.AddField(
            model_name='stellenplan',
            name='th',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stellenplan.teilhaushalte', verbose_name='Teilhaushalt'),
        ),
        migrations.CreateModel(
            name='Produkte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField(verbose_name='Haushaltsjahr')),
                ('produkt', models.IntegerField(blank=True, null=True, verbose_name='Produktnummer')),
                ('bezeichnung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Produktbezeichnung')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orga.gemeinden', verbose_name='Gemeinde')),
                ('teilhaushalt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stellenplan.teilhaushalte', verbose_name='Teilhaushalt')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
                'db_table': 'Produkte',
            },
        ),
        migrations.AlterUniqueTogether(
            name='stellenplan',
            unique_together={('haushaltsjahr', 'gemeinde', 'stelle_nr')},
        ),
    ]
