# Generated by Django 6.0.2 on 2026-05-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0009_koerperschaftstypen_gemeinden_koerperschaftstyp'),
        ('stellenplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sollaederungsgrund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grund_code', models.SmallIntegerField(verbose_name='Grund-Code')),
                ('grund_bez', models.CharField(max_length=255, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Solländerungsgrund',
                'verbose_name_plural': 'Solländerungsgründe',
                'db_table': 'Sollaederungsgruende',
            },
        ),
        migrations.CreateModel(
            name='HHJGDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haushaltsjahr', models.IntegerField(unique=True, verbose_name='Haushaltsjahr')),
                ('start', models.DateField(verbose_name='Startdatum')),
                ('ende', models.DateField(verbose_name='Enddatum')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orga.gemeinden', verbose_name='Gemeinde')),
            ],
            options={
                'verbose_name': 'Haushaltsjahr',
                'verbose_name_plural': 'Haushaltsjahre',
                'db_table': 'Haushaltsjahre',
            },
        ),
        migrations.AlterUniqueTogether(
            name='stellenplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stellenplan',
            name='HHJGDE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stellenplan.hhjgde', verbose_name='Haushaltsjahr (HHJGDE)'),
        ),
        migrations.AddField(
            model_name='stellenplansoll',
            name='HHJGDE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stellenplan.hhjgde', verbose_name='Haushaltsjahr (HHJGDE)'),
        ),
        migrations.AlterUniqueTogether(
            name='stellenplan',
            unique_together={('HHJGDE', 'stelle_nr')},
        ),
        migrations.AddField(
            model_name='stellenplansoll',
            name='soll_aend_grund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stellenplan.sollaederungsgrund', verbose_name='Grund der Solländerung'),
        ),
        migrations.RemoveField(
            model_name='stellenplan',
            name='gemeinde',
        ),
        migrations.RemoveField(
            model_name='stellenplan',
            name='haushaltsjahr',
        ),
    ]
