# Generated by Django 6.0.2 on 2026-03-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgaben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufg_gliederung', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gliederungsnummer')),
                ('errichtung', models.DateTimeField(blank=True, null=True, verbose_name='Aufgenommen am')),
                ('aufgabe_bez', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aufgabenbezeichnung')),
                ('grundlage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rechtsgrundlage')),
                ('aufg_beschreibung', models.CharField(blank=True, max_length=500, null=True, verbose_name='Beschreibung')),
                ('aufgabentyp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aufgabentyp')),
                ('gv_zuordnung', models.IntegerField(blank=True, null=True, verbose_name='Geschäftsverteilung')),
                ('verkn_vg', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verknüpfte VG')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'db_table': 'Aufgaben',
            },
        ),
        migrations.CreateModel(
            name='Gemeinden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemeindenummer', models.IntegerField(unique=True, verbose_name='Gemeindenummer')),
                ('gemeinde', models.CharField(max_length=255, verbose_name='Gemeindename')),
            ],
            options={
                'verbose_name': 'Gemeinde',
                'verbose_name_plural': 'Gemeinden',
                'db_table': 'Gemeinden',
            },
        ),
        migrations.CreateModel(
            name='OrgGliederungstiefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gliederungstiefe', models.IntegerField(verbose_name='Tiefenstufe')),
                ('bezeichnung', models.CharField(max_length=255, verbose_name='Bezeichnung')),
            ],
            options={
                'verbose_name': 'Org. Gliederungstiefe',
                'db_table': 'OrgGliederungstiefe',
            },
        ),
        migrations.CreateModel(
            name='TaetigkeitenORG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taet_id', models.IntegerField(verbose_name='Tätigkeits-ID')),
                ('taet_nr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tätigkeitsnummer')),
                ('bezeichnung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bezeichnung')),
                ('fallzahl', models.IntegerField(blank=True, null=True, verbose_name='Fallzahl')),
                ('bearbeitungszeit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bearbeitungszeit (min)')),
                ('anteil_vzae', models.IntegerField(blank=True, null=True, verbose_name='Anteil VZAE (%)')),
            ],
            options={
                'verbose_name': 'Tätigkeit (ORG)',
                'verbose_name_plural': 'Tätigkeiten (ORG)',
                'db_table': 'TaetigkeitenORG',
            },
        ),
        migrations.CreateModel(
            name='Geschaeftsverteilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gvid', models.IntegerField(verbose_name='GV-ID')),
                ('haushaltsjahr', models.IntegerField(verbose_name='Haushaltsjahr')),
                ('gesch_v_nr', models.CharField(blank=True, max_length=50, null=True, verbose_name='GV-Nummer')),
                ('gv_bez', models.CharField(blank=True, max_length=255, null=True, verbose_name='GV-Bezeichnung')),
                ('beschreibung_lang', models.TextField(blank=True, null=True, verbose_name='Ausführliche Beschreibung')),
                ('produkt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Produkt')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orga.gemeinden', verbose_name='Gemeinde')),
            ],
            options={
                'verbose_name': 'Geschäftsverteilung',
                'db_table': 'Geschaeftsverteilung',
            },
        ),
        migrations.CreateModel(
            name='Organisationseinheiten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=50, unique=True, verbose_name='ORG-Kürzel')),
                ('organisationseinheit', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('unterste', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unterste Ebene (J/N)')),
                ('neben', models.BooleanField(default=False, verbose_name='Nebenstelle')),
                ('stab', models.BooleanField(default=False, verbose_name='Stabsstelle')),
                ('jahr', models.DateField(blank=True, null=True, verbose_name='Gültig ab')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orga.gemeinden', verbose_name='Gemeinde')),
            ],
            options={
                'verbose_name': 'Organisationseinheit',
                'verbose_name_plural': 'Organisationseinheiten',
                'db_table': 'Organisationseinheiten',
            },
        ),
    ]
