# Generated by Django 6.0.2 on 2026-03-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orga', '0001_initial'),
        ('stellenplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationseinheiten',
            name='th_zuordnung',
            field=models.ManyToManyField(blank=True, null=True, to='stellenplan.teilhaushalte', verbose_name='Teilhaushalt'),
        ),
        migrations.AddField(
            model_name='organisationseinheiten',
            name='ueber_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='untergeordnete', to='orga.organisationseinheiten', verbose_name='Übergeordnete OE'),
        ),
        migrations.AddField(
            model_name='geschaeftsverteilung',
            name='org_einheit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orga.organisationseinheiten', verbose_name='Organisationseinheit'),
        ),
        migrations.AddField(
            model_name='organisationseinheiten',
            name='gliederungstiefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orga.orggliederungstiefe', verbose_name='Gliederungstiefe'),
        ),
        migrations.AddField(
            model_name='taetigkeitenorg',
            name='stelle_nr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stellenplan.stellenplan', verbose_name='Stelle'),
        ),
        migrations.AddField(
            model_name='taetigkeitenorg',
            name='zuord_gvid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orga.geschaeftsverteilung', verbose_name='Zuordnung GV'),
        ),
    ]
