# Generated by Django 6.0.2 on 2026-03-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0003_organisationseinheiten_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgaben',
            name='aufgabenverpflichtung',
            field=models.CharField(blank=True, choices=[('PflichtSV', 'Pflichtaufgabe der Selbstverwaltung'), ('FreiwilligSV', 'Freiwillige Aufgabe der Selbstverwaltung'), ('Auftrag', 'Auftragsangelegenheit'), ('Management', 'Managementaufgabe'), ('Sonstige', 'Sonstige Aufgabe')], max_length=50, null=True, verbose_name='Aufgabenverpflichtung'),
        ),
    ]
