# Generated by Django 6.0.2 on 2026-03-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0004_aufgaben_aufgabenverpflichtung'),
    ]

    operations = [
        migrations.AddField(
            model_name='geschaeftsverteilung',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geschaeftsverteilung',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geschaeftsverteilung',
            name='path',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
