# Generated by Django 6.0.2 on 2026-03-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0005_geschaeftsverteilung_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemeinden',
            name='arbeitgebernummerPPA',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Arbeitgebernummer PPA'),
        ),
        migrations.AddField(
            model_name='gemeinden',
            name='arbeitgebernummerRV',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Arbeitgebernummer RV'),
        ),
        migrations.AddField(
            model_name='gemeinden',
            name='arbeitgebernummerZVK',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Arbeitgebernummer ZVK'),
        ),
    ]
