# Generated by Django 6.0.2 on 2026-03-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0007_organisationseinheiten_aktiv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemeinden',
            name='aktiv',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='gemeinden',
            name='gueltig_bis',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig bis'),
        ),
    ]
