# Generated by Django 6.0.2 on 2026-05-07 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orga', '0008_gemeinden_aktiv_gemeinden_gueltig_bis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koerperschaftstypen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50, unique=True, verbose_name='Körperschaftstyp')),
                ('typ_kurz', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kürzel')),
                ('bezbehoerdenleiter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bezeichnung Behördenleiter')),
                ('prefix', models.CharField(blank=True, max_length=10, null=True, verbose_name='Präfix (z.B. Stdt., Lkr.)')),
            ],
            options={
                'verbose_name': 'Körperschaftstyp',
                'db_table': 'Koerperschaftstypen',
            },
        ),
        migrations.AddField(
            model_name='gemeinden',
            name='Koerperschaftstyp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orga.koerperschaftstypen', verbose_name='Körperschaftstyp'),
        ),
    ]
