# Generated by Django 6.0.2 on 2026-03-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beurteilungstypen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50, verbose_name='Beurteilungstyp')),
                ('beschreibung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Beurteilungstyp',
                'verbose_name_plural': 'Beurteilungstypen',
                'db_table': 'Beurteilungstypen',
            },
        ),
        migrations.CreateModel(
            name='StundenVZAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beamter', models.BooleanField(default=False)),
                ('art', models.CharField(blank=True, max_length=255, null=True)),
                ('urlaubstage', models.IntegerField(blank=True, null=True, verbose_name='Urlaubstage/Jahr')),
                ('stunden', models.CharField(blank=True, max_length=50, null=True, verbose_name='Wochenstunden')),
                ('bis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gültig bis')),
            ],
            options={
                'verbose_name': 'Stunden/VZAE',
                'db_table': 'StundenVZAE',
            },
        ),
        migrations.CreateModel(
            name='Tabellenentgelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gilt_ab', models.DateTimeField(verbose_name='Gültig ab')),
                ('gilt_bis', models.DateTimeField(blank=True, null=True, verbose_name='Gültig bis')),
                ('verg_grp', models.CharField(max_length=50, verbose_name='Vergütungsgruppe')),
                ('stufe', models.IntegerField(blank=True, null=True, verbose_name='Stufe')),
                ('tabellenentgelt', models.IntegerField(blank=True, null=True, verbose_name='Tabellenentgelt (ct)')),
            ],
            options={
                'verbose_name': 'Tabellenentgelt',
                'verbose_name_plural': 'Tabellenentgelte',
                'db_table': 'Tabellenentgelt',
            },
        ),
        migrations.CreateModel(
            name='VergGrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verg_grp', models.CharField(max_length=50, verbose_name='Vergütungsgruppe')),
                ('bezeichnung', models.CharField(blank=True, max_length=255, null=True)),
                ('beamter', models.BooleanField(default=False, verbose_name='Beamtenstelle')),
                ('bo_an', models.CharField(blank=True, max_length=50, null=True, verbose_name='Besoldungsordnung/Anlage')),
            ],
            options={
                'verbose_name': 'Vergütungsgruppe',
                'verbose_name_plural': 'Vergütungsgruppen',
                'db_table': 'VergGrp',
            },
        ),
        migrations.CreateModel(
            name='Personalstamm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pers_nr', models.IntegerField(unique=True, verbose_name='Personalnummer')),
                ('nachname', models.CharField(max_length=255, verbose_name='Nachname')),
                ('vorname', models.CharField(max_length=255, verbose_name='Vorname')),
                ('strasse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Straße/Hausnummer')),
                ('ort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ort')),
                ('telefon', models.CharField(blank=True, max_length=50, null=True)),
                ('mobil', models.CharField(blank=True, max_length=50, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('einsatzort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Einsatzort')),
                ('verheiratet_seit', models.DateTimeField(blank=True, null=True, verbose_name='Verheiratet seit')),
                ('verheiratet_mit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verheiratet mit')),
                ('verwitwet_seit', models.DateTimeField(blank=True, null=True, verbose_name='Verwitwet seit')),
                ('geschieden_seit', models.DateTimeField(blank=True, null=True, verbose_name='Geschieden seit')),
                ('wiederverheiratet_seit', models.DateTimeField(blank=True, null=True, verbose_name='Wiederverheiratet seit')),
                ('wiederverheiratet_mit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wiederverheiratet mit')),
                ('eintritt', models.DateTimeField(blank=True, null=True, verbose_name='Eintrittsdatum')),
                ('eintrittsgrund', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eintrittsgrund')),
                ('austritt', models.DateTimeField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('austrittsgrund', models.CharField(blank=True, max_length=255, null=True, verbose_name='Austrittsgrund')),
                ('beamter', models.BooleanField(default=False, verbose_name='Beamter')),
                ('bda', models.DateTimeField(blank=True, null=True, verbose_name='Beamtendienstalter')),
                ('sonstige', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sonstige Angaben')),
                ('wehrdienst_von', models.DateTimeField(blank=True, null=True, verbose_name='Wehrdienst von')),
                ('wehrdienst_bis', models.DateTimeField(blank=True, null=True, verbose_name='Wehrdienst bis')),
                ('gdb', models.IntegerField(blank=True, null=True, verbose_name='Grad der Behinderung (%)')),
                ('behinderung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Art der Behinderung')),
                ('beh_ausweis_vom', models.DateTimeField(blank=True, null=True, verbose_name='Ausweis ausgestellt am')),
                ('beh_ausweis_vorlagedatum', models.DateTimeField(blank=True, null=True, verbose_name='Ausweis vorgelegt am')),
                ('beh_ausweis_gueltig_bis', models.DateTimeField(blank=True, null=True, verbose_name='Ausweis gültig bis')),
                ('gemeinde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orga.gemeinden', verbose_name='Gemeinde')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Personalstamm',
                'db_table': 'Personalstamm',
            },
        ),
        migrations.CreateModel(
            name='PersFortschritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab_datum', models.DateTimeField(verbose_name='Gültig ab')),
                ('bis_datum', models.DateTimeField(blank=True, null=True, verbose_name='Gültig bis')),
                ('verguetung', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergütungsgruppe')),
                ('stufe', models.IntegerField(blank=True, null=True, verbose_name='Stufe')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Vergütungsfortschritt',
                'verbose_name_plural': 'Vergütungsfortschritt',
                'db_table': 'PersFortschritt',
            },
        ),
        migrations.CreateModel(
            name='Kinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kind', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name des Kindes')),
                ('geburtsdatum', models.DateTimeField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('kinderstatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status (ehelich/adoptiert/...)')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Kind',
                'verbose_name_plural': 'Kinder',
                'db_table': 'Kinder',
            },
        ),
        migrations.CreateModel(
            name='Beurteilungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(verbose_name='Beurteilungsdatum')),
                ('beurteilung_von', models.DateField(blank=True, null=True, verbose_name='Beurteilungszeitraum von')),
                ('beurteilung_bis', models.DateField(blank=True, null=True, verbose_name='Beurteilungszeitraum bis')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note/Ergebnis')),
                ('beurteilender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beurteilender Vorgesetzter')),
                ('bemerkungen', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen')),
                ('beurteilungstyp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personalstamm.beurteilungstypen', verbose_name='Beurteilungstyp (LB/BDB)')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Beurteilung',
                'verbose_name_plural': 'Beurteilungen',
                'db_table': 'Beurteilungen',
            },
        ),
        migrations.CreateModel(
            name='AusWeiterbildung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausbildungsziel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ausbildungsziel')),
                ('ausbildung_bei', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ausbildung bei')),
                ('von', models.DateTimeField(blank=True, null=True, verbose_name='Von')),
                ('bis', models.DateTimeField(blank=True, null=True, verbose_name='Bis')),
                ('bemerkungen', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Aus-/Weiterbildung',
                'verbose_name_plural': 'Aus-/Weiterbildungen',
                'db_table': 'AusWeiterbildung',
            },
        ),
        migrations.CreateModel(
            name='PersSonst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonstiges', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sonstiges')),
                ('zeitraum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zeitraum')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Sonstige Personalangabe',
                'db_table': 'PersSonst',
            },
        ),
        migrations.CreateModel(
            name='Pruefungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prüfungsbezeichnung')),
                ('ort', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prüfungsort')),
                ('abgenommen_durch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Abgenommen durch')),
                ('datum', models.DateTimeField(blank=True, null=True, verbose_name='Prüfungsdatum')),
                ('ergebnis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ergebnis')),
                ('wiederholungspruefung', models.BooleanField(default=False, verbose_name='Wiederholungsprüfung')),
                ('lehrgangszuschuss', models.BooleanField(default=False, verbose_name='Lehrgangszuschuss gewährt')),
                ('bemerkungen_lehrgangszusch', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen Zuschuss')),
                ('zeugnis', models.FileField(blank=True, null=True, upload_to='zeugnisse/', verbose_name='Zeugnis/Urkunde (Datei)')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Prüfung',
                'verbose_name_plural': 'Prüfungen',
                'db_table': 'Pruefungen',
            },
        ),
        migrations.CreateModel(
            name='TaetigkeitenPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oeffentlicher_dienst', models.BooleanField(default=False, verbose_name='Öffentlicher Dienst')),
                ('arbeitgeber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arbeitgeber')),
                ('beginn_der_taet', models.DateTimeField(blank=True, null=True, verbose_name='Beginn der Tätigkeit')),
                ('ende_der_taet', models.DateTimeField(blank=True, null=True, verbose_name='Ende der Tätigkeit')),
                ('art_des_dv', models.CharField(blank=True, max_length=100, null=True, verbose_name='Art des Dienstverhältnisses')),
                ('aufgabengebiet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aufgabengebiet')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Frühere Tätigkeit',
                'verbose_name_plural': 'Frühere Tätigkeiten',
                'db_table': 'TaetigkeitenPersonal',
            },
        ),
    ]
