# Generated by Django 6.0.2 on 2026-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verggrp',
            name='reihenfolge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reihenfolge'),
        ),
    ]
