# Generated by Django 6.0.2 on 2026-07-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0002_verggrp_reihenfolge'),
    ]

    operations = [
        migrations.AddField(
            model_name='stundenvzae',
            name='ab',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig ab'),
        ),
        migrations.AlterField(
            model_name='stundenvzae',
            name='bis',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig bis'),
        ),
        migrations.AlterField(
            model_name='verggrp',
            name='verg_grp',
            field=models.CharField(max_length=50, unique=True, verbose_name='Vergütungsgruppe'),
        ),
    ]
