# Generated by Django 6.0.2 on 2026-07-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0003_stundenvzae_ab_alter_stundenvzae_bis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellenentgelt',
            name='tabellenentgelt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tabellenentgelt (ct)'),
        ),
        migrations.AlterField(
            model_name='tabellenentgelt',
            name='verg_grp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personalstamm.verggrp', verbose_name='Vergütungsgruppe'),
        ),
    ]
