# Generated by Django 6.0.2 on 2026-07-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0004_alter_tabellenentgelt_tabellenentgelt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabellenentgelt',
            name='gilt_ab',
            field=models.DateField(verbose_name='Gültig ab'),
        ),
        migrations.AlterField(
            model_name='tabellenentgelt',
            name='gilt_bis',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig bis'),
        ),
    ]
