# Generated by Django 6.0.2 on 2026-09-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0005_alter_tabellenentgelt_gilt_ab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalstamm',
            name='geburtsdatum',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
    ]
