# Generated by Django 6.0.2 on 2026-09-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0006_personalstamm_geburtsdatum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persfortschritt',
            name='verguetung',
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='ag_sonstiges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='AG Sonstiges'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='ag_sv',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='AG Sozialversicherung'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='ag_zvk',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='AG Zusatzversorgung'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='eingruppierung',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='personalstamm.tabellenentgelt', verbose_name='Vergütung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='entgelt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='entgeltumwandlung',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Entgeltumwandlung'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='entgeltumwandlung_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entgeltumwandlung (Text)'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='gesamt_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Gesamtbrutto'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='kinderzuschlag',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kinderzuschlag'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='sonstige_zulagen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Sonstige Zulagen'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='vwl_ag',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='VWL Arbeitgeberanteil'),
        ),
    ]
