# Generated by Django 6.0.2 on 2026-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0007_remove_persfortschritt_verguetung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalstamm',
            name='geburtsort',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Geburtsort'),
        ),
    ]
