# Generated by Django 6.0.2 on 2026-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0008_personalstamm_geburtsort'),
    ]

    operations = [
        migrations.AddField(
            model_name='persfortschritt',
            name='ag_sonstiges_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AG Sonstiges (Text)'),
        ),
        migrations.AddField(
            model_name='persfortschritt',
            name='bemerkungen',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen'),
        ),
    ]
