# Generated by Django 6.0.2 on 2026-10-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalstamm', '0009_persfortschritt_ag_sonstiges_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verhaeltnistypen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verhaeltnistyp', models.CharField(max_length=50, verbose_name='Dienstverhältnis')),
                ('beschreibung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschreibung')),
                ('beamtet', models.BooleanField(default=False, verbose_name='Beamter')),
            ],
            options={
                'verbose_name': 'Dienstverhältnistypen',
                'verbose_name_plural': 'Dienstverhältnisse',
                'db_table': 'Verhaeltnistypen',
            },
        ),
        migrations.CreateModel(
            name='IstVerguetung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vergzeitraum', models.DateTimeField(verbose_name='Lohndatum')),
                ('anbrutto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Arbeitnehmer Brutto')),
                ('ag_sv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Arbeitgeber Sozialversicherung')),
                ('ag_zvk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Arbeitgeber Zusatzversorgung')),
                ('ag_sonstiges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Arbeitgeber Sonstiges')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
            ],
        ),
        migrations.CreateModel(
            name='Verhaeltnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von', models.DateField(verbose_name='Gültig von')),
                ('bis', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('beschreibung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschreibung')),
                ('befristung', models.BooleanField(default=False, verbose_name='Befristung möglich')),
                ('befristung_umfang', models.IntegerField(blank=True, null=True, verbose_name='Befristung (Monate)')),
                ('befristung_bis', models.DateField(blank=True, null=True, verbose_name='Befristung gültig bis')),
                ('befristung_grund', models.CharField(blank=True, max_length=255, null=True, verbose_name='Befristungsgrund')),
                ('befristung_dokument', models.URLField(blank=True, max_length=500, null=True, verbose_name='Befristungsdokument (URL)')),
                ('pers_nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalstamm.personalstamm', to_field='pers_nr', verbose_name='Mitarbeiter')),
                ('verhaeltnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personalstamm.verhaeltnistypen', verbose_name='Dienstverhältnis')),
            ],
            options={
                'verbose_name': 'Dienstverhältnis',
                'verbose_name_plural': 'Dienstverhältnisse',
                'db_table': 'Verhaeltnis',
            },
        ),
    ]
